# Generated by Django 5.2.7 on 2025-11-18 05:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('MODULE_EXAM', 'Module Exam'), ('COURSE_EXAM', 'Course Exam'), ('ASSIGNMENT', 'Assignment')], max_length=11)),
                ('description', models.TextField()),
                ('no_of_questions', models.PositiveIntegerField()),
                ('pass_marks', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('pass_percentage', models.PositiveIntegerField()),
                ('easy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('medium_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hard_count', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_limit', models.IntegerField(blank=True, null=True)),
                ('estimated_duration_in_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='assessment__title_281404_idx'), models.Index(fields=['created_at'], name='assessment__created_8d828a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('START', 'Start'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], db_index=True, default='START', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='course_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Mcq Single'), ('MCQ_MULTI', 'Mcq Multi'), ('TRUE_FALSE', 'True False'), ('FILL_BLANK', 'Fill Blank'), ('MATCH_PAIRS', 'Match Pairs')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['question_type'], name='assessment__questio_1e0608_idx'), models.Index(fields=['difficulty'], name='assessment__difficu_e9da2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttemptQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=255)),
                ('is_response_correct', models.CharField(choices=[('CORRECT', 'Correct'), ('WRONG', 'Wrong'), ('PARTIAL_CORRECT', 'Partial Correct')], db_index=True, default='WRONG', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_submissions', to='assessment.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_submissions', to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('bank_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_question_bank', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_question', to='assessment.question')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_bank', to='assessment.questionbank')),
            ],
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'assessment'], name='assessment__user_id_7ef3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status'], name='assessment__status_5a0cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['started_at'], name='assessment__started_a9fd56_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattemptquestionsubmission',
            index=models.Index(fields=['attempt'], name='assessment__attempt_0d0f42_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattemptquestionsubmission',
            index=models.Index(fields=['question'], name='assessment__questio_9087b7_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattemptquestionsubmission',
            index=models.Index(fields=['is_response_correct'], name='assessment__is_resp_c8e31a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['title'], name='assessment__title_8c0e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['created_at'], name='assessment__created_a39234_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankquestion',
            index=models.Index(fields=['question_bank', 'order'], name='assessment__questio_cf1ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankquestion',
            index=models.Index(fields=['created_at'], name='assessment__created_324fbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionbankquestion',
            unique_together={('question_bank', 'order')},
        ),
    ]
