# Generated by Django 5.2.7 on 2025-11-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        ("course_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_assessments",
                to="course_management.course",
            ),
        ),
    ]
