# Generated by Django 5.2.7 on 2025-11-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_assessment_course"),
        ("course_management", "0002_remove_video_topic_id_video_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="course",
        ),
        migrations.AddField(
            model_name="assessment",
            name="topic",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_assessment",
                to="course_management.topic",
            ),
        ),
    ]
