# Generated by Django 5.2.7 on 2025-11-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="topic_id",
        ),
        migrations.AddField(
            model_name="video",
            name="topic",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_video",
                to="course_management.topic",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT", "Development"),
                    ("DESIGN", "Design"),
                    ("MARKETING", "Marketing"),
                    ("BUSINESS", "Business"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
