# Generated by Django 5.2.7 on 2025-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0002_remove_video_topic_id_video_topic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("last_requests", models.JSONField(default=list)),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
